### ISSUE TITLE
Import Error No Module Named _curses

### ISSUE THREAD

**Issue by jwdsoft** [alexandreblin/python-can-monitor#14]
I'm trying to use the can monitor
after successfully installing it (pip install -e .)
when I run the command canmonitor either for com port or from log file I get this error

canmonitor -f tests\data\test_data.log
Traceback (most recent call last):
  File "C:\Python35\Scripts\canmonitor-script.py", line 11, in <module>
    load_entry_point('canmonitor', 'console_scripts', 'canmonitor')()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2318, in load
    return self.resolve()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "e:\arduino and reversing\canbus\python arduino canbus\python-can-monitor-master\canmonitor\canmonitor.py", line 4, in <module>
    import curses
  File "c:\python35\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'

**Comment by NoahWallace** [comment]
I figured out his issue by reading this
https://stackoverflow.com/questions/32417379/what-is-needed-for-curses-in-python-3-4-on-windows7
It got me past this error
