### ISSUE TITLE
Sleep Length Too Large

### ISSUE THREAD

**Issue by NoahWallace** [alexandreblin/python-can-monitor#16]
Working with this project, I have exported a cadump file and am now recieving this issue
Python 3.8
pip 19.2.3
```
canmonitor -f F:\WindowsShared\CanBus\candump-2020-03-03_232741.log
Traceback (most recent call last):
  File "c:\python-can-monitor\canmonitor\canmonitor.py", line 26, in reading_loop
    frame_id, data = source_handler.get_message()
  File "c:\python-can-monitor\canmonitor\source_handler.py", line 115, in get_message
    return self._parse_from_candump(line)
  File "c:\python-can-monitor\canmonitor\source_handler.py", line 126, in _parse_from_candump
    time.sleep((abstime - self.clock) / self.speed_scale)
OverflowError: sleep length is too large
```

**Comment by kstahl48** [comment]
Try changing all the numbers in the parenthesis in candump-2020-03-03_232741.log to smaller numbers. Or change them to all 0's.
